### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by niladam** [webfactor/laravel-backpack-instant-fields#20]
Just a thank you issue! -- Really, thank you for your hard work!

**Comment by tswonke** [comment]
Thank you very much for your feedback! :-)

I maybe have an idea to make this easier... Hope I will find the time for it.

**Comment by niladam** [comment]
@tswonke i'm looking forward to that. Need a hand ?

**Comment by tswonke** [comment]
Thanks for asking :-)

I thought about passing the foreign controller in the field itself. Maybe this could make the handling more easy. You are welcome to play around with it - or with other ideas? I'm open for suggestions.
