### ISSUE TITLE
All fields are market as required

### ISSUE THREAD

**Issue by prodixx** [webfactor/laravel-backpack-instant-fields#38]
I have setup instantFields on 3 models. Each CRUD Model have optional and required fields but when the modal shows up i have red asterisc to all of the fields labels. 

On the standard CRUD update form everything is ok. 

I've also tried to comment backpack's setRequiredFields  and add setAjaxStoreRequest but with no luck.

**Comment by tswonke** [comment]
This is not easy to answer, we don't have an issue like this in our projects. Maybe you can provide some code?
