### ISSUE TITLE
Laravel 6.x + Backpack 4.x

### ISSUE THREAD

**Issue by pleone** [webfactor/laravel-backpack-instant-fields#39]
## Detailed description

Would be nice to have support for latest versions of laravel (> 6.x) and backpack ( > 4.x )

**Comment by tswonke** [comment]
I have added Laravel 6 support in composer.json.

This is untested, I don't know whether there are any breaks.
And I'm sorry to tell you, that we have currently no plans to upgrade this package to Backpack v4.

**Comment by samuk190** [comment]
@tswonke  what last version that does it work? on backpack v3

**Comment by tswonke** [comment]
We are using it on v3.5.14

**Comment by samuk190** [comment]
> We are using it on v3.5.14

Thanks. I'm still subscribed to the package if somedays release v4.. the features are insanely good but lack of the matrix input is bad and it is coming on in 1-2 weeks

**Comment by samuk190** [comment]
@tswonke  just for curiosity I tested on backpack v4 and the error was sharedreportcontroller on ajax request.
 I Think its a easy error to fix so it can be compatible. Because the table layout, buttons and some methods are working fine...

**Comment by pleone** [comment]
Sadly i solved passing to nova.

**Comment by tswonke** [comment]
I don't know which changes were made for Backpack v4. As far as I know there was discussion about how routes are now defined (and can be extended in packages).

We moved to Nova some months ago for some reasons. That's why we currently won't maintain this package. But if someone provides a fully tested pull request to support Backpack v4 (including readme) I will gladly bump this version to v4 as well.

**Comment by samuk190** [comment]
> I don't know which changes were made for Backpack v4. As far as I know there was discussion about how routes are now defined (and can be extended in packages).
> 
> We moved to Nova some months ago for some reasons. That's why we currently won't maintain this package. But if someone provides a fully tested pull request to support Backpack v4 (including readme) I will gladly bump this version to v4 as well.

Thanks. If you know why ShareReportController is not found when using with() -> function ajax( possible causes?)
I think if I fix that it will solve the issue with v4
